usr/share/doc-base/libmgesysutils
usr/share/doc/libmgesysutils/api
usr/share/doc/libmgesysutils/AUTHORS usr/share/doc/libmgesysutils1-doc
usr/share/doc/libmgesysutils/ChangeLog usr/share/doc/libmgesysutils1-doc
usr/share/doc/libmgesysutils/COPYING usr/share/doc/libmgesysutils1-doc
usr/share/doc/libmgesysutils/NEWS usr/share/doc/libmgesysutils1-doc
usr/share/doc/libmgesysutils/README usr/share/doc/libmgesysutils1-doc

