usr/include/*
usr/lib/*/lib*.a
usr/lib/*/lib*.la
usr/lib/*/lib*.so
usr/lib/*/pkgconfig/*
usr/share/man/man3/*
usr/share/doc/libmgesysutils/AUTHORS usr/share/doc/libmgesysutils-dev
usr/share/doc/libmgesysutils/ChangeLog usr/share/doc/libmgesysutils-dev
usr/share/doc/libmgesysutils/COPYING usr/share/doc/libmgesysutils-dev
usr/share/doc/libmgesysutils/NEWS usr/share/doc/libmgesysutils-dev
usr/share/doc/libmgesysutils/README usr/share/doc/libmgesysutils-dev

