usr/share/doc-base/libmgesysutils-int
usr/share/doc/libmgesysutils/int
usr/share/doc/libmgesysutils/AUTHORS usr/share/doc/libmgesysutils2-int-doc
usr/share/doc/libmgesysutils/ChangeLog usr/share/doc/libmgesysutils2-int-doc
usr/share/doc/libmgesysutils/COPYING usr/share/doc/libmgesysutils2-int-doc
usr/share/doc/libmgesysutils/NEWS usr/share/doc/libmgesysutils2-int-doc
usr/share/doc/libmgesysutils/README usr/share/doc/libmgesysutils2-int-doc

