usr/share/doc-base/libmgesysutils
usr/share/doc/libmgesysutils/api/html/*
usr/share/doc/libmgesysutils/api/libmgesysutils-doxy-*.tar.gz
usr/share/doc/libmgesysutils/AUTHORS usr/share/doc/libmgesysutils-doc
usr/share/doc/libmgesysutils/ChangeLog usr/share/doc/libmgesysutils-doc
usr/share/doc/libmgesysutils/COPYING usr/share/doc/libmgesysutils-doc
usr/share/doc/libmgesysutils/NEWS usr/share/doc/libmgesysutils-doc
usr/share/doc/libmgesysutils/README usr/share/doc/libmgesysutils-doc

